add scatter plot props for corresponding visualization
VEuPathDB/web-components pull request #115
Opened 2021-05-04 00:12 UTC by moontrip

added three new props to the scatter plot component for visualization: displayLegend, displayLibraryControls, and setMargin. These props are useful for handling the grid view of the scatter plot viz.

2021-05-04 19:37 UTC, dmfalke requested changes
See inline comment requesting a change.

2021-05-04 19:37 UTC, dmfalke commented on src/plots/ScatterAndLinePlotGeneral.tsx
> +  setMargin?: { l: number; r: number; b: number; t: number };
This seem redundant with the `margin` property defined [here](https://github.com/VEuPathDB/web-components/blob/84f30c59b0e9a471d21a02b373c9c336cf69b94d/src/plots/PlotlyPlot.tsx#L23). Can this be removed?

2021-05-04 20:01 UTC, moontrip commented on src/plots/ScatterAndLinePlotGeneral.tsx
> +  setMargin?: { l: number; r: number; b: number; t: number };
@dmfalke Thank you for finding that redundant prop! 👍 I just remembered that actually it was me to add the margin prop at PlotlyPlot component long time ago haha. I have removed it and changed corresponding part that used setMargin prop

2021-05-05 03:49 UTC, dmfalke approved these changes

2021-05-05 03:50 UTC, dmfalke commented
Thanks for making these changes, @moontrip. Feel free to merge this at your convenience.

2021-05-05 12:29 UTC, merged