box plot component for EDA
VEuPathDB/web-components pull request #138
Opened 2021-06-02 17:33 UTC by moontrip

Unlike Bob had implemented for pre-existing box plot component that include the computation of quartiles etc., Plotly.js simply demands raw data for box plot. Thus I have made simpler box plot component for EDA, temporarily named as boxplotEDA to distinguish from pre-existing one. 

This is functional, but just made it as draft PR as this is probably not included in the Gates demo

2021-06-22 19:12 UTC, bobular reviewed
Looks good - just a few style and organisational issues.

Will look at the web-eda PR ASAP next.

2021-06-22 19:12 UTC, bobular commented on src/plots/BoxplotEDA.tsx
> +import { useEffect, useMemo, useState } from 'react';
Can we remove this source file before merging please?

2021-06-22 19:12 UTC, bobular commented on src/stories/plots/Boxplot.stories.tsx
> +  title: 'Plots/Boxplot',
Coordinating with #150 and before merging, please make sure all stories are "storybook control" enabled.  Thanks.

2021-06-22 19:31 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    // seems like plotly bug: y[0] or x[0] should not be empty array (e.g., with overlay variable)
@bobular well actually I found that kind of bug when using overlay variable. I believe that in most cases, there would be no bug but if using overlay variable, there may be the case. I just checked your case, country vs water trips weekely but y[0] was not empty (actually `outliers` response) - at GEMS1 case control.

The test case is at its story file, Multiple Dataset, which Kenya has the outliers with empty array at the first array (y[0])

finally, I tried various way, but only y[0] = [null] worked so...

2021-06-22 19:37 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    if (
yep will do that

2021-06-22 19:38 UTC, moontrip commented on src/plots/Boxplot.tsx
> +function isArrayOfNumbers(value: any): value is number[] {
wow I didn't know that. It was used to find and test the aforementioned bug but forgot to remove.

2021-06-22 19:41 UTC, moontrip commented on src/stories/plots/Boxplot.stories.tsx
> +  title: 'Plots/Boxplot',
Well actually I have a plan to merge your changes in the future after your PR will be merged into the main. 
storybook control is already in there, `With Storybook Control` story

2021-06-22 19:42 UTC, moontrip commented on src/plots/BoxplotEDA.tsx
> +import { useEffect, useMemo, useState } from 'react';
Certainly I have a plan to remove them, BoxplotEDA and its story file. Will do that this time

2021-06-22 22:59 UTC, bobular commented on src/plots/Boxplot.tsx
> +    // seems like plotly bug: y[0] or x[0] should not be empty array (e.g., with overlay variable)
(My GEMS example does create `y[0] == []` - after subsetting on countries so the first country is Mozambique.)

2021-06-22 23:19 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    // seems like plotly bug: y[0] or x[0] should not be empty array (e.g., with overlay variable)
Ah, I see. I didn't use filter/subsetting so that might be the reason why I could not get your case 👍

2021-07-06 18:24 UTC, moontrip commented
updated box plot components for tidy-up and corresponding viz. Perhaps this can be out of draft PR so I am changing it

2021-07-07 13:28 UTC, bobular requested changes
Hi DK - good job accommodating the tidy-up changes.

There are some major decisions to take about handling date data, which will need to be resolved before tidying up this ticket and merging.

In the meantime, you could remove a few DKDKs ;-) 

Note that I made this review *before* looking at the sister PR in web-eda

2021-07-07 13:28 UTC, bobular commented on src/stories/plots/Boxplot.stories.tsx
> +      mean: [2008.8639, 2009.0816, 2009.0021],
These aren't dates!
I suggest something like this 
```
      mean: ['2008-10-02', '2009-07-22', '2009-01-13'],
```

2021-07-07 13:28 UTC, bobular commented on src/plots/Boxplot.tsx
> +  console.log('data =', data);
console log

2021-07-07 13:28 UTC, bobular commented on src/plots/Boxplot.tsx
> +    const [independentAxis, dependentAxis] =
Does it help (or hinder? perhaps eating memory for large data) to use `useMemo` for `const data = ...` ?

2021-07-07 13:28 UTC, bobular commented on src/plots/Boxplot.tsx
> +  dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category';
Seeing `'longitude'` and `'category'` here makes me worry this is too EDA-centric.

Only the `'date'` value is used/implemented and tested with a story (dependentAxis dates for "Year Dataset" story).  (It seems impossible to select a date variable as dependentVariable in the EDA boxplot viz...?)

Also, there is no use-case for having the `independentValueType` prop, is there?  Won't the independent variable always be a categorical variable?   The independent axis needs to be handled the same way as barplot, I think.  Barplot.tsx doesn't (currently) specify `layout.xaxis.type`.

I suggest remove the `independentValueType` prop because, like Barplot at the moment, every compatible variable seems to be categorical-string.

`dependentValueType` should just have `'number' | 'date'` options until other options are required in the future.

If we need to do something special with categorical number variables in the future, we can come back and revisit.

2021-07-07 13:28 UTC, bobular commented on src/plots/Boxplot.tsx
> +    //DKDK don't forget this for multiple datasets
DKDK...

2021-07-07 13:28 UTC, bobular commented on src/types/plots/boxplot.ts
> +  median: number[];
So if we are removing support for date-based dependent variables (which is probably fine, but we need to clarify with the backend team) - then we can also remove the `dependentValueType` prop, can't we?

I see now that the removal of `string[]` types here make my `yearData` story example give a TS error.

TLDR: either offer full date support for dependentAxis or none at all!

2021-07-07 13:28 UTC, bobular commented on src/types/plots/boxplot.ts
> +  rawData?: number[][] | string[][];
Why is `string[][]` still here if it was removed for mean/median/q1/q3 etc?

2021-07-07 13:59 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    if (
@bobular thank you for your comments and suggestions. I will check this part. DKDK and console.log would be cleaned up in the final stage when all stuffs will be approved :)

2021-07-07 14:01 UTC, moontrip commented on src/plots/Boxplot.tsx
> +  independentValueType?:
@bobular I have separate them to be simpler for the use of typing at its viz: certainly I may define data part separately like histogram. In my opinion, we may separate them as they are not a part of Data structure.

2021-07-07 14:04 UTC, moontrip commented on src/stories/plots/Boxplot.stories.tsx
> +      mean: [2008.8639, 2009.0816, 2009.0021],
@bobular as indicated at the story file, those are actual response data format for that case. I just tested with Gem1 study and in that case there was no date data - other study may have date data though: any case (X/Y variables and study) you can suggest testing at viz ?

2021-07-07 14:05 UTC, moontrip commented on src/plots/Boxplot.tsx
> +  console.log('data =', data);
@bobular yep I will do that later

2021-07-07 14:09 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    const [independentAxis, dependentAxis] =
@bobular not sure if useMemo will be much helpful in this simple case.

2021-07-07 14:12 UTC, moontrip commented on src/plots/Boxplot.tsx
> +  dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category';
@bobular Initially I just set number and date, however, I had to change it because of type errors at viz, which they suggest using those types. I don't think it would hurt anyway. Yeah I agree that `independentValueType` is an overkill at this stage.

2021-07-07 14:12 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    //DKDK don't forget this for multiple datasets
@bobular yep I will get rid of them later 😄

2021-07-07 14:16 UTC, moontrip commented on src/types/plots/boxplot.ts
> +  median: number[];
@bobular I just followed the [data API spec](https://veupathdb.github.io/EdaDataService/api.html#resources:/apps/pass/visualizations/boxplot:post) as median is currently listed as number[]. It could be incorrect so we need to make sure of it at first.

2021-07-07 14:18 UTC, moontrip commented on src/types/plots/boxplot.ts
> +  rawData?: number[][] | string[][];
@bobular The data API doc did not clarify the type of the rawData so I just left it as number or string. Again, I tried to follow the data API doc for defining all response data types.

2021-07-07 17:56 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    if (
@bobular updated this with your suggestion 👍

2021-07-07 17:57 UTC, moontrip commented on src/plots/Boxplot.tsx
> +  console.log('data =', data);
@bobular removed this

2021-07-07 17:58 UTC, moontrip commented on src/plots/Boxplot.tsx
> +  dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category';
@bobular removed  `independentValueType` prop (and at viz too)

2021-07-07 17:58 UTC, moontrip commented on src/plots/Boxplot.tsx
> +    //DKDK don't forget this for multiple datasets
@bobular removed all DKDK 😃

2021-07-07 18:13 UTC, moontrip commented
@bobular I made comment at each suggestion if I addressed them. The others are debatable so I just leave them as is

2021-07-08 15:59 UTC, bobular commented on src/stories/plots/Boxplot.stories.tsx
> +      mean: [2008.8639, 2009.0816, 2009.0021],
Oh I see - well that's a data problem - it's a date stored as a number.  Not our problem.  The story should use real dates though (or we remove all date implementation from the plot component, see below)

There are plenty of real dates (stored as dates) in GEMS1 - but the variable constraints do not allow these to be chosen in the EDA for boxplot y-axis.  I assume this means we will not implement it, but I will ask on the backend Slack for confirmation.

2021-07-08 16:04 UTC, moontrip commented on src/stories/plots/Boxplot.stories.tsx
> +      mean: [2008.8639, 2009.0816, 2009.0021],
That makes sense. I could not see any date-like variables when selecting y-axis variable so suspected as well it did not allow date by the constraints. Thank you for handling that possible backend issue 👍

2021-07-08 16:43 UTC, bobular commented on src/plots/Boxplot.tsx
> +  dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category';
I can't see why dependentValueType needs all those options. The type error you see is on the viz side because you're passing `variable.type` which is typed as `'string' | 'number' | 'date' | 'longitude' | 'category'` into the Boxplot component.

I don't think that's a good enough reason to copy those types into Plot Components.  The tail shouldn't wag the dog!

2021-07-08 16:56 UTC, bobular commented on src/types/plots/boxplot.ts
> +  median: number[];
Ah yes, the API spec says no dates (so does Nupur on #eda-backend)

2021-07-08 16:57 UTC, bobular commented on src/types/plots/boxplot.ts
> +  rawData?: number[][] | string[][];
Looks like we should remove the string options here - based on what we have just learned.

2021-07-08 17:03 UTC, bobular commented on src/plots/Boxplot.tsx
> +  independentValueType?:
I happy to agree with you

2021-07-08 17:27 UTC, moontrip commented on src/plots/Boxplot.tsx
> +  dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category';
Yes you are right as I am sending variable.type directly. Certainly I can also send only 'number' or 'date' value from viz by checking variable.type with condition. But I think it is better to just pass variable.type value without such an additional check/computing as it is more generic ? 

`dependentValueType` at plot component is just used for assigning `type` parameter at plotly's axis, `date | linear/undefined`,  and actually it only matters when dependentValueType = 'date', so it is not that harmful to have other values beyond number and date ?

If you still think it should be `number | date` only then I can change it :)

2021-07-08 17:34 UTC, moontrip commented on src/types/plots/boxplot.ts
> +  rawData?: number[][] | string[][];
yeah I will remove string[][] in there (for both rawData and outliers)

2021-07-08 17:38 UTC, moontrip commented on src/plots/Boxplot.tsx
> +  dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category';
since no 'date' data is expected at boxplot, perhaps we can either remove that props or just leave it as number| date - I will work for the latter

2021-07-08 17:50 UTC, bobular commented
I think we have two choices

1.
Keep the dependentValueType prop:
'number' | 'date' and defaults to 'number'

Fix the BoxplotData to allow number or string everywhere.

2.
Remove all date handling.  EDA doesn't want it, and if we need it for
another client later, we can add it.

On Thu, Jul 8, 2021 at 6:39 PM DK ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/plots/Boxplot.tsx
> <https://github.com/VEuPathDB/web-components/pull/138#discussion_r666395472>
> :
>
> >    dependentAxisLabel?: string;
>    /** set the range of the dependent axis (optional)  */
>    dependentAxisRange?: NumberOrDateRange;
>    /** show the rawData (if given) - optional */
>    showRawData?: boolean;
>    /** Show the mean as an extra dotted line in the box - optional */
>    showMean?: boolean;
> +  /** show/hide independent axis tick label */
> +  showIndependentAxisTickLabel?: boolean;
> +  /** show/hide dependent axis tick label */
> +  showDependentAxisTickLabel?: boolean;
> +  /** independentValueType: 'string' | 'number' | 'date' | 'longitude' | 'category' */
> +  independentValueType?:
> +    | 'string'
> +    | 'number'
> +    | 'date'
> +    | 'longitude'
> +    | 'category';
> +  /** dependentValueType: 'string' | 'number' | 'date' | 'longitude' | 'category' */
> +  dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category';
>
> since no 'date' data is expected at boxplot, perhaps we can either remove
> that props or just leave it as number| date - I will work for the latter
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/VEuPathDB/web-components/pull/138#discussion_r666395472>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACLLH4QG37OZ4ZXGDEN5VDTWXPDXANCNFSM457FTYGA>
> .
>

2021-07-08 18:12 UTC, moontrip commented
> I think we have two choices 1. Keep the dependentValueType prop: 'number' | 'date' and defaults to 'number' Fix the BoxplotData to allow number or string everywhere. 2. Remove all date handling. EDA doesn't want it, and if we need it for another client later, we can add it.
> […](#)
> On Thu, Jul 8, 2021 at 6:39 PM DK ***@***.***> wrote: ***@***.**** commented on this pull request. ------------------------------ In src/plots/Boxplot.tsx <[#138 (comment)](https://github.com/VEuPathDB/web-components/pull/138#discussion_r666395472)> : > dependentAxisLabel?: string; /** set the range of the dependent axis (optional) */ dependentAxisRange?: NumberOrDateRange; /** show the rawData (if given) - optional */ showRawData?: boolean; /** Show the mean as an extra dotted line in the box - optional */ showMean?: boolean; + /** show/hide independent axis tick label */ + showIndependentAxisTickLabel?: boolean; + /** show/hide dependent axis tick label */ + showDependentAxisTickLabel?: boolean; + /** independentValueType: 'string' | 'number' | 'date' | 'longitude' | 'category' */ + independentValueType?: + | 'string' + | 'number' + | 'date' + | 'longitude' + | 'category'; + /** dependentValueType: 'string' | 'number' | 'date' | 'longitude' | 'category' */ + dependentValueType?: 'string' | 'number' | 'date' | 'longitude' | 'category'; since no 'date' data is expected at boxplot, perhaps we can either remove that props or just leave it as number| date - I will work for the latter — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub <[#138 (comment)](https://github.com/VEuPathDB/web-components/pull/138#discussion_r666395472)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AACLLH4QG37OZ4ZXGDEN5VDTWXPDXANCNFSM457FTYGA> .

2021-07-14 10:51 UTC, bobular approved these changes

2021-07-14 10:52 UTC, bobular commented
Sorry for the delay - I didn't see this had gone stale.  I just approved the changes!

2021-07-21 13:11 UTC, jtlong3rd approved these changes

2021-07-21 13:17 UTC, merged