Plot props/API tidy-up
VEuPathDB/web-components pull request #150
Opened 2021-06-14 11:56 UTC by bobular

We have accumulated a variety of different ways of handling plot sizing, and control of things like "displayLibraryControls" and "staticPlot" - a lot of these things are re-implemented in actual plot components (e.g. Histogram or Boxplot) but could and should easily be handled by the PlotlyPlot wrapper.  No Plot component props will have dependencies on Plotly.

I have started to tidy-up and standardise our code.

One thing I would like early feedback on is the `data` prop.

The new way of doing thing is that a component like Boxplot has a `boxplotData` prop (it used to be called `data`) - the Boxplot component processes `boxplotData` into `data` and passes it to the PlotlyPlot wrapper.

Is there a way to do it with the data props always called `data`?

2021-06-14 11:58 UTC, bobular commented
Note: I know Boxplot was a bad example to start with...
We already have a [commit](https://github.com/VEuPathDB/web-components/commit/fc032c0454e3c9605390563bcf80c62888cd9922) in the `boxplot` branch that removes the Plotly `Datum` dependency.  I haven't cherry-picked that commit into this repo yet.  I will work on the other plot components after getting feedback on the data prop.

2021-06-14 12:00 UTC, bobular commented on src/plots/PlotlyPlot.tsx
> +export default function PlotlyPlot(props: PlotProps & PlotParams) {
This is the big change I would like feedback on.

2021-06-14 15:48 UTC, dmfalke commented
@bobular, I don't understand your question about the `data` param.

2021-06-14 15:57 UTC, dmfalke commented
@bobular would this address your question?

```typescript
interface PlotProps<T> {
  data: T;
  ...
}

interface BoxPlotData {
  ...
}

interface BoxPlot extends PlotProps<BoxPlotData> {
  ...
}
```

2021-06-14 16:03 UTC, bobular commented
Thanks - it might! I hadn't considered that approach.  Will keep you posted.

2021-06-14 16:06 UTC, dmfalke commented
I think you will also need to do this:

```typescript
export default function PlotlyPlot(props: Exclude<PlotProps, 'data'> & PlotParams) {
```

2021-06-15 09:12 UTC, bobular commented
Aha, thanks, I did wonder about doing an Exclude to deal with this.

To avoid that I renamed the `data` prop on "our side" as `plotData`.  But
then there was no nice way to ensure that components extending PlotProps
contained plotData.  I think this does the trick, thanks!!


On Mon, Jun 14, 2021 at 5:06 PM Dave Falke ***@***.***> wrote:

> I think you will also need to do this:
>
> export default function PlotlyPlot(props: Exclude<PlotProps, 'data'> & PlotParams) {
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/VEuPathDB/web-components/pull/150#issuecomment-860805300>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACLLH26EIMIKRG3KJYGLMLTSYSH5ANCNFSM46VCVQAQ>
> .
>

2021-06-15 10:07 UTC, bobular commented
Thanks again @dmfalke - it worked with `Omit` - now the API is much cleaner :-)

2021-06-18 13:53 UTC, bobular commented
Fixes #148

2021-06-18 13:55 UTC, bobular commented
Fixes https://github.com/VEuPathDB/web-eda/issues/148 but this probably won't be automagically linked...

2021-06-22 18:01 UTC, chowington commented on src/plots/Boxplot.tsx
> -    <div style={{ position: 'relative', width: width, height: height }}>
@bobular The issue of the spinner not being centered is due to this `div` being removed. It wraps the plot and the spinner and is given the same width and height of the plot. The spinner centers itself within its container (seen in `Spinner.tsx`, so it centers inside this div and therefore centers over the plot as well.

2021-06-22 18:01 UTC, chowington commented on src/plots/Boxplot.tsx
> -    <div style={{ position: 'relative', width: width, height: height }}>
You could probably just reintroduce this div in `PlotlyPlot`, I imagine

2021-06-22 18:29 UTC, chowington commented on src/stories/plots/MosaicPlot.stories.tsx
> +EmptyData.args = {
Should be `EmptyDataLoading.args`. Causes this story to break. I've done this a couple times myself when copy/pasting!

2021-06-22 18:31 UTC, chowington commented
Great job on this Bob! Looks like a very flexible system 👍

2021-06-22 19:17 UTC, dmfalke commented
I've skimmed through the changes, and this is looking really great. I plan to take a more thorough look later. One thought that occurred to me is how these changes will relate to faceting. Basically I want to make sure we are optimizing for that use case and won't need to reimplement a bunch of stuff.

2021-06-22 19:45 UTC, jtlong3rd approved these changes
This looks great! I had two minor style suggestions.

2021-06-22 19:45 UTC, jtlong3rd commented on src/stories/api/githubDates.ts
>  export const getCreatedDateData = async (
Consider either:

1. Deleting the `async` keyword. (It's redundant since you're not using `await`.)

OR

2. Replacing `.then` / `.catch` with `await` / `try-catch`.

2021-06-22 19:45 UTC, jtlong3rd commented on src/components/plotControls/HistogramControls.tsx
> +        {opacity != undefined && onOpacityChange && (
I'd recommend `!= null` instead of `!= undefined`. Our [standard ESLint config](https://www.npmjs.com/package/@veupathdb/eslint-config) enforces the [`smart` version of the `eqeqeq` rule](https://eslint.org/docs/rules/eqeqeq#smart).

2021-06-22 19:45 UTC, jtlong3rd commented on src/components/plotControls/HistogramControls.tsx
> +        {displayLegend != undefined && toggleDisplayLegend && (
Ditto.

2021-06-22 19:45 UTC, jtlong3rd commented on src/components/plotControls/HistogramControls.tsx
> +        {displayLibraryControls != undefined && toggleLibraryControls && (
Ditto.

2021-06-22 21:46 UTC, dmfalke requested changes
So far, I only have one requested change.

2021-06-22 21:46 UTC, dmfalke commented on src/plots/PlotlyPlot.tsx
> +export interface PlotProps<T extends UnionOfPlotDataTypes> {
This part gives me pause. I don't think it is necessary to specify `T extends UnionOfPlotDataTypes`. I think `T` can simply be generic.

```suggestion
export interface PlotProps<T> {
```

2021-06-22 23:23 UTC, bobular commented on src/plots/Boxplot.tsx
> -    <div style={{ position: 'relative', width: width, height: height }}>
Thanks - I think I tried that and it didn't work...  But div placement is above my payscale ;-)

2021-06-23 00:13 UTC, bobular commented on src/stories/api/githubDates.ts
>  export const getCreatedDateData = async (
Hmm, it compiles and works with or without the `async` keyword there.
But without it, my editor advises "This may be converted to an async function [80006]"
It's too late (at night) for me to learn more about this right now.

2021-06-23 00:16 UTC, bobular commented
> I've skimmed through the changes, and this is looking really great. I plan to take a more thorough look later. One thought that occurred to me is how these changes will relate to faceting. Basically I want to make sure we are optimizing for that use case and won't need to reimplement a bunch of stuff.

So far I've been hoping that standardising things like `displayLegend` (or is it `showLegend` lol) will be put us in good stead for faceting, but maybe there is more to it!

2021-06-23 00:24 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +        {opacity != undefined && onOpacityChange && (
Thanks - I've found a few more elsewhere in the codebase.

Presumably `foo == undefined` should be `foo == null` too.
I'll do it more carefully in the morning though ;-)

2021-06-23 10:21 UTC, bobular commented on src/stories/api/githubDates.ts
>  export const getCreatedDateData = async (
I did some more reading and added an `await` before the fetch.
Not sure why none of the previous variants caused compiler or IDE warnings!
Thanks for the pointers :+1: 
```
export const getCreatedDateData = async (
  url: string
): Promise<Array<EventData>> => {
  return await fetch(url)
    .then((response) => {
      if (response.ok) {
        return response.json();
      } else {
        throw new Error(
          'Response not as expected. Probably exceeded API rate limit.'
        );
      }
    })
    .then((json) => {
      return json.map((item: any) => ({
        id: item.id,
        date: item.created_at,
      }));
    })
    .catch((error) => {
      console.log(error.message);
    });
};
```

2021-06-23 10:45 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +        {opacity != undefined && onOpacityChange && (
Cleaned up the whole repo in this regard (=== undefined -> == null,  !=undefined -> != null, etc) - tested affected components via checking stories.  All good

2021-06-23 10:51 UTC, bobular commented on src/plots/PlotlyPlot.tsx
> +export interface PlotProps<T extends UnionOfPlotDataTypes> {
Thanks - I thought it would be helpful to constrain the XxxData types to ones we knew about, but I suppose it's a pain to maintain UnionOfPlotDataTypes.  The latter could probably be retired at some point (it is mainly a usePlotControls thing, I think) but not now.

2021-06-23 11:20 UTC, bobular commented on src/plots/Boxplot.tsx
> -    <div style={{ position: 'relative', width: width, height: height }}>
Tried again - worked this time. Thanks!

2021-06-23 19:37 UTC, dmfalke approved these changes

2021-06-23 19:43 UTC, moontrip approved these changes

2021-06-23 21:08 UTC, chowington approved these changes

2021-06-29 15:54 UTC, dmfalke commented on src/stories/api/githubDates.ts
>  export const getCreatedDateData = async (
The primary purpose of using `async` is to avoid using Promise chains. While the code you have above is perfectly valid, it's not entirely conventional.

First, there isn't any real value in adding the `await` in the code above. It pretty much equivalent to the previous code.

A more conventional use of an `async` function would look like this (note the use of `await` to "unwrap" promises so that you can interact directly with the value.

```typescript
export const getCreatedDateData = async (
  url: string
): Promise<Array<EventData>> => {
  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(
      'Response not as expected. Probably exceeded API rate limit.'
    );
    const json = await response.json();
    return json.map((item: any) => ({
      id: item.id,
      date: item.created_at,
    }));
  }
  catch (error) {
    console.log(error.message);
  }
};
```

2021-06-29 16:15 UTC, jtlong3rd commented on src/stories/api/githubDates.ts
>  export const getCreatedDateData = async (
Just so we're all on the same page, @dmfalke's suggestion is exactly what I had in mind for `Replacing .then / .catch with await / try-catch`.

2021-06-29 20:54 UTC, dmfalke approved these changes

2021-06-29 21:43 UTC, bobular commented on src/stories/api/githubDates.ts
>  export const getCreatedDateData = async (
Thanks both.  I have done as suggested. It definitely reads nicer!

2021-06-30 10:37 UTC, merged