Add color palette default and prop
VEuPathDB/web-components pull request #187
Opened 2021-08-12 16:19 UTC by chowington

Fixes https://github.com/VEuPathDB/web-components/issues/127

The color palette works for the following plots:

- Barplot
- Boxplot
- Histogram
- XYPlot

and doesn't work for the following plots:

- Heatmap (not qualitative)
- Mosaic
- Pie

2021-08-12 16:44 UTC, jtlong3rd reviewed
Aside from one small suggestion, looks good to me!

2021-08-12 16:44 UTC, jtlong3rd commented on src/plots/PlotlyPlot.tsx
>        plotlyProps.layout,
Add `colorPalette` to this `useMemo` dependency array.

2021-08-12 17:07 UTC, dmfalke requested changes
This is looking good. I think XYPlot does work, but the colors are hard-coded in `XYPlot.stories.tsx`. Could you add a story without the hard-coded colors? Thanks!

2021-08-12 19:56 UTC, chowington commented on src/plots/PlotlyPlot.tsx
>        plotlyProps.layout,
Done!

2021-08-12 19:58 UTC, chowington commented
> 
> 
> This is looking good. I think XYPlot does work, but the colors are hard-coded in `XYPlot.stories.tsx`. Could you add a story without the hard-coded colors? Thanks!

Done! Looks like the color palette gets used by the dots and the smoothed mean, but not the confidence interval

2021-08-12 20:05 UTC, moontrip commented
@chowington for scatter plot, there exists a sort of a grouped plot like raw data (marker), smoothed mean, and confidence interval (CI) for smoothed mean with raw option, which would follow the same color: CI uses opacity lower than 1 but the same color with corresponding marker and line (smoothed mean).

2021-08-13 00:50 UTC, jtlong3rd approved these changes

2021-08-16 20:57 UTC, merged

2021-08-17 18:21 UTC, bobular commented on src/plots/PlotlyPlot.tsx
> +    colorPalette,
I'd have put the default here - 

```
colorPalette = ColorPaletteDefault,
```
Just in case it gets used more than once and we forget to `colorPalette ?? ColorPaletteDefault` each time we use it.

But this was only ever going to be used once - so no need for a post-merge change.  Maybe next time we're working on this file we could change it.

2021-08-17 18:29 UTC, chowington commented on src/plots/PlotlyPlot.tsx
> +    colorPalette,
Right, of course I should have! That's the second duh moment in two days for me, lol. Should have added you as the third reviewer! Thanks Bob

2021-08-17 18:39 UTC, bobular commented
It is working for Mosaic, isn't it? @chowington 

![image](https://user-images.githubusercontent.com/308639/129781147-87db5dc8-3d16-49d7-b0b8-2d2d36828d7c.png)

Pie uses the colorway too if you disable `defaultColorGen` (I made it `yield undefined`)

![image](https://user-images.githubusercontent.com/308639/129781822-2ab9ec54-4674-49ed-8ab2-8fd115cde5de.png)


I'm confused about one thing: Barplot, Histogram and Boxplot all use the ColorPaletteAddon but XYPlot, Pie and Mosaic don't.
Ah but then I see it's here in PlotlyPlot.tsx, which makes sense
```
export default function PlotlyPlot<T>(
  props: Omit<PlotProps<T>, 'data'> & PlotParams & ColorPaletteAddon
) {
```
Does that mean we should remove the addon from Barplot, Histogram and Boxplot?

2021-08-17 18:51 UTC, bobular commented
> @chowington for scatter plot, there exists a sort of a grouped plot like raw data (marker), smoothed mean, and confidence interval (CI) for smoothed mean with raw option, which would follow the same color: CI uses opacity lower than 1 but the same color with corresponding marker and line (smoothed mean).

You get the desired cyan colour for the smoothed mean CI with the following minor tweak to the story

```
diff --git a/src/stories/plots/XYPlot.stories.tsx b/src/stories/plots/XYPlot.stories.tsx
index 303f257..ac89213 100755
--- a/src/stories/plots/XYPlot.stories.tsx
+++ b/src/stories/plots/XYPlot.stories.tsx
@@ -1053,7 +1053,7 @@ function processInputData<T extends number | string>(
         // type: 'line',
         type: 'scattergl',
         // here, line means upper and lower bounds
-        line: { color: 'transparent', shape: 'spline' },
+        line: { color: defineColors ? 'transparent' : undefined, shape: 'spline' },
       });
     }
```

2021-08-17 19:18 UTC, moontrip commented
> > @chowington for scatter plot, there exists a sort of a grouped plot like raw data (marker), smoothed mean, and confidence interval (CI) for smoothed mean with raw option, which would follow the same color: CI uses opacity lower than 1 but the same color with corresponding marker and line (smoothed mean).
> 
> You get the desired teal/cyan colour for the smoothed mean CI with the following minor tweak to the story
> 
> ```
> diff --git a/src/stories/plots/XYPlot.stories.tsx b/src/stories/plots/XYPlot.stories.tsx
> index 303f257..ac89213 100755
> --- a/src/stories/plots/XYPlot.stories.tsx
> +++ b/src/stories/plots/XYPlot.stories.tsx
> @@ -1053,7 +1053,7 @@ function processInputData<T extends number | string>(
>          // type: 'line',
>          type: 'scattergl',
>          // here, line means upper and lower bounds
> -        line: { color: 'transparent', shape: 'spline' },
> +        line: { color: defineColors ? 'transparent' : undefined, shape: 'spline' },
>        });
>      }
> ```

@bobular just FYI: certainly it would show teal/cyan color but the main purpose of the `line:` prop in there is not to show upper/lower bound lines: if it is defined like that, it would shows bound lines and a vertical line at the max of confidence interval

2021-08-17 20:03 UTC, bobular commented
Ah yes it does show boundary lines in the story, but not in the
ScatteplotViz so I don't think we need to worry.

On Tue, Aug 17, 2021 at 8:19 PM DK ***@***.***> wrote:

> @chowington <https://github.com/chowington> for scatter plot, there
> exists a sort of a grouped plot like raw data (marker), smoothed mean, and
> confidence interval (CI) for smoothed mean with raw option, which would
> follow the same color: CI uses opacity lower than 1 but the same color with
> corresponding marker and line (smoothed mean).
>
> You get the desired teal/cyan colour for the smoothed mean CI with the
> following minor tweak to the story
>
> diff --git a/src/stories/plots/XYPlot.stories.tsx b/src/stories/plots/XYPlot.stories.tsx
> index 303f257..ac89213 100755
> --- a/src/stories/plots/XYPlot.stories.tsx
> +++ b/src/stories/plots/XYPlot.stories.tsx
> @@ -1053,7 +1053,7 @@ function processInputData<T extends number | string>(
>          // type: 'line',
>          type: 'scattergl',
>          // here, line means upper and lower bounds
> -        line: { color: 'transparent', shape: 'spline' },
> +        line: { color: defineColors ? 'transparent' : undefined, shape: 'spline' },
>        });
>      }
>
> @bobular <https://github.com/bobular> just FYI: certainly it would show
> teal/cyan color but the main purpose of the line: prop in there is not to
> show upper/lower bound lines: if it is defined like that, it would shows
> bound lines and a vertical line at the max of confidence interval
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/VEuPathDB/web-components/pull/187#issuecomment-900566397>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACLLHZRLF6DZMUMW4TVALDT5KY2RANCNFSM5CBTHTXQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-19 18:47 UTC, chowington commented
> 
> 
> It is working for Mosaic, isn't it? @chowington
> 
> ![image](https://user-images.githubusercontent.com/308639/129781147-87db5dc8-3d16-49d7-b0b8-2d2d36828d7c.png)
> 
> Pie uses the colorway too if you disable `defaultColorGen` (I made it `yield undefined`)
> 
> ![image](https://user-images.githubusercontent.com/308639/129781822-2ab9ec54-4674-49ed-8ab2-8fd115cde5de.png)
> 
> I'm confused about one thing: Barplot, Histogram and Boxplot all use the ColorPaletteAddon but XYPlot, Pie and Mosaic don't.
> Ah but then I see it's here in PlotlyPlot.tsx, which makes sense
> 
> ```
> export default function PlotlyPlot<T>(
>   props: Omit<PlotProps<T>, 'data'> & PlotParams & ColorPaletteAddon
> ) {
> ```
> 
> Does that mean we should remove the addon from Barplot, Histogram and Boxplot?
> 
> EDIT:
> I moved the ColorPaletteAddon usage in PlotlyPlot.tsx and now none of the individual components need to use it.
> 
> ```
> export interface PlotProps<T> extends ColorPaletteAddon {
> ```

Hi Bob! I made ColorPalette an Addon because not all plots used it (at this point only Heatmap doesn't), therefore it should not be provided as a prop for all plots. So I left it out of the PlotProps interface. Adding it to that interface means that Heatmap has it as a prop, which is confusing. However the implementation was the same for all plots that used ColorPalette, so I just put the implementation in PlotlyPlot by extending the actual PlotlyPlot incoming props type directly.

2021-08-19 20:33 UTC, bobular commented
Aha, thanks for the explanation, @chowington - so yes, we should move it out of PlotlyPlot's props into each of the components.  A minor faff, but it makes sense for heatmap and any future plots that don't use it.  I'll make a ticket directly in web-components.