Truncated axis for histogram
VEuPathDB/web-components pull request #195
Opened 2021-08-25 01:27 UTC by moontrip

this PR is a kind of restructuring the previous PR, #186, with the recent changes by Bob and his suggestions. The overall structure is simplified and organized better, than before.

It may be still be complex mainly because the nature of the dependent axis (Y-axis): dependent axis is correlated with independent axis' range control while the opposite case is not. That is, in many cases, the change of independent axis range (via plot control) also makes changes for the data range of dependent axis: min/max of Y-axis data changes. While, the change of dependent axis range via its plot control changes nothing in data aspect, i.e., just changing display only, not data. 

The storybook screenshot shows its changes but dependent axis control does not reflect the behavior correctly (because y-axis min/max do not change with respect to x-axis control). But other two screenshots (number and date variables in the independent axis) taken from histogram filter shows more correct behaviors.

![storybook-range1](https://user-images.githubusercontent.com/12802305/130711035-5b70cdb4-6041-4dca-88c3-900a383dffe5.png)

![india-icemr-number1](https://user-images.githubusercontent.com/12802305/130711042-95ecf5b0-eb07-4639-9f08-f5c7f19e0ee4.png)

![india-icemr-date1](https://user-images.githubusercontent.com/12802305/130711046-923c0d49-45d8-4c0a-acdc-b1ae2349a10a.png)

2021-08-25 10:15 UTC, bobular commented
Hi @moontrip  Functionally, why does this have a lower truncation warning?

![image](https://user-images.githubusercontent.com/308639/130772888-dc9d4eb3-b86c-4eb2-b8ab-37a904c11279.png)

2021-08-25 11:22 UTC, bobular requested changes
I'm sorry but it's still too complex and my guidance/spec hasn't been followed. Please see the individual comments.
Please note also my [separate report](https://github.com/VEuPathDB/web-components/pull/195#issuecomment-905369492) of the storybook not behaving correctly.

2021-08-25 11:22 UTC, bobular commented on src/stories/plots/Histogram.stories.tsx
> +    dependentAxisMin =
Something feels wrong about modifying a non-const inside the useEffect - but it may be OK.

However, the values are first set at line 379, and are then overwritten here - with another flatMap/orderBy that is copy-pasted from `dataDependentAxisMinMax()`.

2021-08-25 11:31 UTC, bobular commented on src/plots/Histogram.tsx
> +  dataDependentAxisRange?: NumberRange;
[Sorry, I forgot to add this comment to the previous review.  Luckily github cached it.]

There's no need to know the range of the dependent axis if the user hasn't entered a range (which is provided as `dependentAxisRange`).

Why not?  Because as described in the outline of 
"If axisRange undefined, or its min or max are undefined, just `return axisRange`"
[here](https://github.com/VEuPathDB/web-components/blob/0c06ff836b584636c3a2b79c8139518b1deb0a32/src/plots/Histogram.tsx#L450) if a range hasn't been provided by the user, then there is no need to do any range extension or warning rectangles.  Also explained [here](https://github.com/VEuPathDB/web-components/pull/186#issuecomment-897557690).

2021-08-25 12:37 UTC, moontrip commented
> Hi @moontrip Functionally, why does this have a lower truncation warning?
> 
> ![image](https://user-images.githubusercontent.com/308639/130772888-dc9d4eb3-b86c-4eb2-b8ab-37a904c11279.png)

@bobular First of all, thank you for your detailed review and comments 👍 I will reply them one by one.

For this one, actually it works correctly. Note that I have added 0 value data at story for better tests (like this lower truncation), so the min/max of the data becomes [0, 99]. The display range of dependent axis corresponding independent axis range control is [7, 99], thus it should have lower truncation warning - perhaps the 0 tick label at the Y-axis confused you, which is the tick in between [-4.95, 7]

2021-08-25 12:39 UTC, moontrip commented on src/components/widgets/NumberAndDateRangeInputs.tsx
> +  if (validator && (required || rangeBounds))
@bobular I am sorry that this is my mistake. I have tested a couple of cases and forgot to revert it to the original format you have made.

2021-08-25 13:08 UTC, bobular commented
> 
> 
> > Hi @moontrip Functionally, why does this have a lower truncation warning?
> > ![image](https://user-images.githubusercontent.com/308639/130772888-dc9d4eb3-b86c-4eb2-b8ab-37a904c11279.png)
> 
> @bobular First of all, thank you for your detailed review and comments 👍 I will reply them one by one.
> 
> For this one, actually it works correctly. Note that I have added 0 value data at story for better tests (like this lower truncation), so the min/max of the data becomes [0, 99]. The display range of dependent axis corresponding independent axis range control is [7, 99], thus it should have lower truncation warning - perhaps the 0 tick label at the Y-axis confused you, which is the tick in between [-4.95, 7]

I don't think that's how it works.  If I provide x-axis range 4 to 10, the displayed values go from 7 to 23 but the default behaviour of Plotly is still to automatically set the y-axis from 0 to whatever (in this case the max is still 100 because the whole of `data` is passed to `Histogram` - really I guess we should pass xFilteredBins to the component from the story).  If the user doesn't touch the y-axis range controls, there is no way that the data can be truncated - because we are sending an `dependentAxisRange: undefined` to the Histogram on purpose - to let Plotly figure out the y-axis range.

![image](https://user-images.githubusercontent.com/308639/130795370-3bacb93f-f007-4b01-a376-e5f06d90c440.png)

So, again - there's no need to pass a dependentAxisRange if the user hasn't specified one.

2021-08-25 13:09 UTC, moontrip commented on src/stories/plots/Histogram.stories.tsx
> +  let { dependentAxisMin, dependentAxisMax } = dataDependentAxisMinMax(
@bobular No not really. We need to know both `dependentAxisMin/Max` and `defaultDependentAxisMin/Max` for working the truncation of dependent axis correctly: this is one of the part that makes things complicated as I mentioned at [my first comment](https://github.com/VEuPathDB/web-components/pull/195#issue-719175561). 

You have set a condition to check axisTruncationConfig for dependent axis at story file, only based on the change (or user's input) of dependent axis range control. However, there is another case of the change (or user's input) of **independent** axis range control that often changes the dependent axis values, like [your screenshot (and my answer)](https://github.com/VEuPathDB/web-components/pull/195#issuecomment-905464120). Thus, I have added the condition based on `dependentAxisMin/Max` and `defaultDependentAxisMin/Max`, e.g., for upper truncation of dependent axis (see my inline comment):

```
    const topTruncated =
      (dependentAxisRange?.max != null &&
        xFilteredBins.filter((bin) => bin.count > dependentAxisRange.max)
          .length > 0) ||         //DKDK this is the part you have set
      (dependentAxisMax != null &&
        defaultDependentAxisMax != null &&
        defaultDependentAxisMax !== dependentAxisMax);   //DKDK Additionally, I have set this condition to detect the change by independent axis range control

```

If you think we don't need to show truncation of dependent axis caused by independent axis range control, then perhaps overall logic may become a bit simplified. But considering the purpose of truncation axis, I think that the second condition I have used above should also be considered.

2021-08-25 13:35 UTC, moontrip commented
> > > Hi @moontrip Functionally, why does this have a lower truncation warning?
> > > ![image](https://user-images.githubusercontent.com/308639/130772888-dc9d4eb3-b86c-4eb2-b8ab-37a904c11279.png)
> > 
> > 
> > @bobular First of all, thank you for your detailed review and comments 👍 I will reply them one by one.
> > For this one, actually it works correctly. Note that I have added 0 value data at story for better tests (like this lower truncation), so the min/max of the data becomes [0, 99]. The display range of dependent axis corresponding independent axis range control is [7, 99], thus it should have lower truncation warning - perhaps the 0 tick label at the Y-axis confused you, which is the tick in between [-4.95, 7]
> 
> I don't think that's how it works. If I provide x-axis range 4 to 10, the displayed values go from 7 to 23 but the default behaviour of Plotly is still to automatically set the y-axis from 0 to whatever (in this case the max is still 100 because the whole of `data` is passed to `Histogram` - really I guess we should pass xFilteredBins to the component from the story). If the user doesn't touch the y-axis range controls, there is no way that the data can be truncated - because we are sending an `dependentAxisRange: undefined` to the Histogram on purpose - to let Plotly figure out the y-axis range.
> 
> ![image](https://user-images.githubusercontent.com/308639/130795370-3bacb93f-f007-4b01-a376-e5f06d90c440.png)
> 
> So, again - there's no need to pass a dependentAxisRange if the user hasn't specified one.

@bobular Thank you for your detailed explanation. I think that we firstly need to clarify the scope of dependent axis truncation. Will we handle the dependent axis truncation irrelevant to independent axis range control ? As I said in [my previous comment](https://github.com/VEuPathDB/web-components/pull/195#discussion_r695735179),  there is a case that independent axis range control make changes the min/max of dependent axis to original data's min/max of dependent axis without independent axis range control. I thought we would consider this case, but your speaking sounds like no and let them be mutually independent each other.

2021-08-25 13:48 UTC, bobular commented on src/stories/plots/Histogram.stories.tsx
> +  let { dependentAxisMin, dependentAxisMax } = dataDependentAxisMinMax(
I don't think we need to worry too much about the logic in a story file.  What matters is that we have a Histogram component that behaves as follows

- IF truncationConfig.dependentAxis.min IS TRUE AND dependentAxisRange IS FULLY DEFINED THEN extend the range (using dependentAxisRange - 5%) and later use the difference between this extended range.min and the original unextended range.min to determine whether or not to draw a gray rectangle (if original range is undefined - don't draw a rectangle)
- IF truncationConfig.dependentAxis.max IS TRUE AND dependentAxisRange IS FULLY DEFINED THEN extend the range (using dependentAxisRange + 5%) and later use the difference between this extended range.max and the original unextended range.max to determine whether or not to draw a gray rectangle (if original range is undefined - don't draw a rectangle)

And the same for the independent axis.

2021-08-25 13:52 UTC, moontrip commented on src/components/widgets/NumberAndDateRangeInputs.tsx
> +  /** DKDK check truncated axis */
@bobular I fully agree with your opinion 👍: I also thought of similar one to have a custom component or simply Notification component at HistogramFilter.

2021-08-25 13:54 UTC, bobular commented
> @bobular Thank you for your detailed explanation. I think that we firstly need to clarify the scope of dependent axis truncation. Will we handle the dependent axis truncation irrelevant to independent axis range control ? As I said in [my previous comment](https://github.com/VEuPathDB/web-components/pull/195#discussion_r695735179), there is a case that independent axis range control make changes the min/max of dependent axis to original data's min/max of dependent axis without independent axis range control. I thought we would consider this case, but your speaking sounds like no and let them be mutually independent each other.

As I said above, don't worry about the logic of when the truncation is detected.

The incoming `truncationConfig` props will say whether or not to draw a rectangle.  If the range for that axis is not explicitly provided (as `dependentAxisRange` or `independentAxisRange`) then do not draw the rectangle (but maybe log something to the console to say that the component was unable to extend the axis with a truncation graphic because the explicit range was not given).

But, again, we never expect axis truncation to occur without the user specifying the axis ranges explicitly.

2021-08-25 14:03 UTC, moontrip commented on src/stories/plots/Histogram.stories.tsx
> +  let { dependentAxisMin, dependentAxisMax } = dataDependentAxisMinMax(
@bobular Sounds great! That dependency I have been considering made things much complicated. If we just think of each range control separately for truncation, then overall implementation will be much simpler 😃 Will work for that.

2021-08-28 17:20 UTC, bobular approved these changes
This is great! Nice and simple ;-) 

Just needs some tidy up (DKDK etc) and the dependencies thing I commented on.

2021-08-28 17:20 UTC, bobular commented on src/plots/Histogram.tsx
> +    independentAxisRange,
Could you double check the dependencies please?  Seems they should include
```
        standardIndependentAxisRange,
        standardDependentAxisRange,
        extendedIndependentAxisRange,
        extendedDependentAxisRange
```

2021-08-28 17:20 UTC, bobular commented on src/plots/Histogram.tsx
> +    //DKDKDK with the truncated axis, negative values need to be checked for log scale
Nice

2021-08-28 21:28 UTC, moontrip commented on src/plots/Histogram.tsx
> +    independentAxisRange,
@bobular thank you for your review. Yes I didn't clean them up yet but I have just pushed.

As for dependencies, I think that they can also be used if we want to clarify them explicitly: I just shortened the dependencies. Below are the reasons.

For `standardIndependentAxisRange`, it depends on `data.valueType`, `independentAxisRange`, and `binSummaries` (see its dependencies when using `useMemo` hook). `data.valueType` changes with `data.series` (this is listed as one of dependencies), `independentAxisRange` is also included as one of dependencies. `binSummaries` actually relies on `data.series`. For this reason, `standardIndependentAxisRange` is not required to be a dependency. Concerning `standardDependentAxisRange`, it is just `dependentAxisRange` that is already listed as one of dependency.

As for `extendedIndependentAxisRange` and `extendedDependentAxisRange`, they are a function of `standardIndependentAxisRange` or `standardDependentAxisRange`, `axisTruncationConfig` (already in the dependency), and `data.valueType` (see the function call, `extendAxisRangeForTruncations()`. So, I think no need to add them as dependencies.

2021-08-30 12:45 UTC, jtlong3rd approved these changes

2021-08-30 13:11 UTC, merged