Update entity diagram UI to represent 1:1 and 1:many relationships
VEuPathDB/web-components pull request #336
Opened 2022-04-01 14:51 UTC by jernestmyers

Addresses issue #326

Current code is hardcoded to only render repeated measures as a 1:many relationship. I will update when backend includes the necessary fields/properties.

The current implementation looks as follows:
**Amazonia ICEMR Brazil Cohor**
![image](https://user-images.githubusercontent.com/69446567/161287312-fd9fff74-35a6-4b50-b639-cfbdfaa74417.png)

**GEMS1 Case Control**
![image](https://user-images.githubusercontent.com/69446567/161287918-cd6e9644-e111-44a6-8739-e559f2101d34.png)

2022-04-13 21:55 UTC, asizemore commented
Hey @jernestmyers !! Just checking out the screenshots it looks really good!

Can we please decrease the stroke width? Maybe like strokeWidth of 2 and nodeSize when expanded 4.5? (my hack to keep the circle the same size but decrease the stroke width)

2022-04-14 13:08 UTC, jernestmyers commented
Thanks for the feedback! I'll make those adjustments this morning.

2022-04-14 15:52 UTC, jernestmyers commented
@asizemore I ended up reducing the `nodeSize` to 4.25 after integrating the new 1:many boolean data. Every entity I have checked thus far has `isManyToOneWithParent` set to `true` and `nodeSize = 4.5` felt a bit big in that case. But I'm happy to bump it back up to 4.5 if that's preferred.

**Amazonia Brazil**
![image](https://user-images.githubusercontent.com/69446567/163426853-ef50aa47-0e67-457f-9702-6019f51c2562.png)

**GEMS 1 Case Control**
![image](https://user-images.githubusercontent.com/69446567/163427040-79cf33b4-36cf-45b5-9d83-04cd08d631fc.png)

2022-04-14 17:46 UTC, dmfalke requested changes
All of this looks great, with the exception of one issue, for which I left a comment.

2022-04-14 17:46 UTC, dmfalke commented on src/EntityDiagram/EntityDiagram.stories.tsx
> +  EUPATH_0000776: {
The property name on this line should also be changed to `EUPATH_0000776`:
https://github.com/VEuPathDB/web-components/blob/346a968e647ca37ef539dca819e697c25076d050/src/EntityDiagram/EntityDiagram.stories.tsx#L21. As it is, I get an error in the storybook when switching the size.

2022-04-14 17:53 UTC, jernestmyers commented on src/EntityDiagram/EntityDiagram.stories.tsx
> +  EUPATH_0000776: {
Ah, I had changed from `GEMS_HouseObs` to `EUPATH_0000776` because the code was using the `id` property to determine if something was 1:many. Now that we rely on `isManyToOneWithParent`, I was changing it back to `GEMS_HouseObs` but forgot to replace it there as well.

Would you agree I should just go back to `GEMS_HouseObs` in that case for consistency?

2022-04-14 17:55 UTC, dmfalke commented on src/EntityDiagram/EntityDiagram.stories.tsx
> +  EUPATH_0000776: {
Yeah, that sounds good!

2022-04-14 18:02 UTC, asizemore commented
@jernestmyers the 4.25 size looks great! Good call!

2022-04-14 18:04 UTC, dmfalke approved these changes

2022-04-14 18:08 UTC, merged