changing control text color to black
VEuPathDB/web-components pull request #337
Opened 2022-04-07 18:54 UTC by moontrip

This PR related to https://github.com/VEuPathDB/web-eda/issues/1011

Danica asked me to change control's text colors into black, not light gray.

2022-04-08 16:57 UTC, bobular requested changes

2022-04-08 16:57 UTC, bobular commented on src/components/widgets/NumberAndDateInputs.tsx
> +          style={{ color: 'black' }}
Please could you make all these like the following:

```
  color: disabled ? MEDIUM_GRAY : 'black'
```
See BinWidthControl.tsx and Switch.tsx for prior examples.

Thanks!

2022-04-10 05:00 UTC, moontrip commented on src/components/widgets/NumberAndDateInputs.tsx
> +          style={{ color: 'black' }}
@bobular Thank you for your suggestion! 👍 I missed that point. Note that I also changed NumberAndDateRangeInputs component with the same approach for "to" text haha. Now texts are shown in medium gray when X axis variable is ordinal/categorical - screenshot is attached for example.

![lineplot-ordinal](https://user-images.githubusercontent.com/12802305/162602119-541be06a-714a-4b3c-b14e-5d0cd217b5af.png)

2022-04-10 13:51 UTC, moontrip commented
@bobular Thank you for taking care of the changes in your `Slider` component/widget! 👍 I saw that max() part at the widget but I was hesitant to mess up your calculation in there without in-depth knowledge. I made changes following your suggestions at web-components, https://github.com/VEuPathDB/web-components/pull/337/commits/7a916be60f6abaa3e8d584fbf8fc4a7e41573c3a, and it seems to work great! Here is my screenshot on a lineplot case and now bin width is in the single line!

![binWidth](https://user-images.githubusercontent.com/12802305/162621420-1e282929-ccca-4b7c-bd58-b490c7bd410f.png)

2022-04-11 11:40 UTC, bobular approved these changes
Looks great. No need for the `// add nowrap` or `// simplyfying width` comments, in my opinion.

2022-04-11 12:14 UTC, merged