remembering the selection of mouse tool
VEuPathDB/web-components pull request #354
Opened 2022-05-19 02:26 UTC by moontrip

This addresses https://github.com/VEuPathDB/web-eda/issues/971 with corresponding web-eda PR.

2022-05-19 13:27 UTC, bobular requested changes
I was going to suggest that you export a MouseModes type from MouseTools, but I see you already do!!

Please could you import that into the Stories (and perhaps also export a `const defaultMouseMode : MouseMode = 'default'` so you can say

```
  const [mouseMode, setMouseMode] = useState<MouseMode>(defaultMouseMode);
```
?

This would make it more future-proof to the addition of more modes!


I also recommend changing the `setMouseMode` property to `onMouseModeChange` to be more consistent (though I see we are not very consistent with the use of `Changed` and `Change`)
I notice on the EDA side you have called it `onMouseModeChange`

2022-05-19 15:15 UTC, moontrip commented
@bobular Thank you for your review and suggestions! 👍 I have addressed your feedbacks.

2022-08-01 12:55 UTC, bobular approved these changes
Looks great, but see my suggestions :-)

2022-08-01 12:55 UTC, bobular commented on src/map/MapVEuMap.tsx
> +  mouseMode: 'default' | 'magnification';
We could save some typing/maintenance with
```suggestion
  mouseMode: MouseMode;
```

2022-08-01 12:55 UTC, bobular commented on src/map/MapVEuMap.tsx
> +  onMouseModeChange: (value: 'default' | 'magnification') => void;
```suggestion
  onMouseModeChange: (value: MouseMode) => void;
```

2022-08-01 19:33 UTC, merged