fix a chartmarker bug
VEuPathDB/web-components pull request #444
Opened 2023-01-30 22:41 UTC by moontrip

This will fix the bug I mentioned at https://github.com/VEuPathDB/web-eda/issues/1586

So, the issue was that some data/marker do not have color info, e.g., when data.value = 0 then no data.color exists, but svg does not like the empty value of `fill` attribute. Thus, I have added a dummy color (white) for no data.color. This manual assignment won't matter because if data.value = 0, then height of the data becomes 0 so its color is actually ignored anyway.

Here are screenshot after this fix: as compared to the problematic screenshots at the https://github.com/VEuPathDB/web-eda/issues/1586.

a) SCORE S. mansonni CRT study
![map-bug-no-data-color-fixed](https://user-images.githubusercontent.com/12802305/215612298-13e75f8b-bf3d-479d-995c-ff07405de52f.png)

b) SCORE Mozambique (Full screen map)
![mozambique map error fixed](https://user-images.githubusercontent.com/12802305/215612366-4c1189e0-caf9-461a-8730-833540544226.png)

2023-01-31 23:54 UTC, bobular requested changes

2023-01-31 23:54 UTC, bobular commented on src/map/ChartMarker.tsx
> +      (el.color ?? 'rgb(255,255,255)').replace(/\s/g, '') +
I think the best thing to do here is use `'silver'` as the default. I don't particularly like it, but it's consistent with DonutMarker.  The problem is that the storybook story has a value of 0. If it was non-zero (which I think makes a better story), we would want the bar to be visible.  Otherwise we should make the `color` prop mandatory!

2023-01-31 23:57 UTC, bobular commented on src/map/ChartMarker.tsx
> +      (el.color ?? 'rgb(255,255,255)').replace(/\s/g, '') +
Thanks for spotting the nasty bug!
The SVG syntax error kills the rest of the marker.

#432 will sort this, but sadly it's not a "must have" for the next release or two

2023-02-01 14:23 UTC, moontrip commented on src/map/ChartMarker.tsx
> +      (el.color ?? 'rgb(255,255,255)').replace(/\s/g, '') +
@bobular Thank you for your comments. It does not matter we use silver, white, etc. Although I didn't check how to create data/marker at useMapMarkers hook at web-eda, a general pattern concerning the bug was that data.color is undefined when data.value = 0. The story's data actually came from one of real data in the first screenshot case.

Anyway, I will change it to silver as it does not matter much to resolve this bug.

2023-02-22 15:28 UTC, moontrip commented
@bobular Just for a reminder, I have addressed your feedback before so it would be great if you can check this out again 👍

2023-02-23 15:35 UTC, moontrip commented
This PR is closed as https://github.com/VEuPathDB/web-components/pull/445 is merged: this bug was also applied at the PR

2023-02-23 15:35 UTC, closed without merging