Entity diagram improvements
VEuPathDB/web-components pull request #84
Opened 2021-03-29 15:30 UTC by chowington

- Combine the two entity diagram components into one
- Implement precise shading
- Fix mini diagram tooltips

2021-03-29 20:50 UTC, dmfalke requested changes
This looks great!

A few requests:
1. Get rid of `ExpandedDiagram.tsx` and `MiniDiagram.tsx`. I think the combined one should be sufficient.
2. I see some React key warnings being logged in the console. Can you address these? See https://reactjs.org/link/warning-keys.

2021-03-30 13:02 UTC, bobular requested changes
Looks good Connor.

Just the duplicated type definition that needs attention, and I recommend merging #86 so the story can be adjusted on the fly by testers.

Could you also add a bit of padding/margin around the diagram (as per Steve's suggestion) and maybe also drop-shadow?

2021-03-30 14:06 UTC, chowington commented on src/EntityDiagram/Types.ts
>  export interface ShadingData {
> 
> 
> This looks great!
> 
> A few requests:
> 
>     1. Get rid of `ExpandedDiagram.tsx` and `MiniDiagram.tsx`. I think the combined one should be sufficient.
> 
>     2. I see some React key warnings being logged in the console. Can you address these? See https://reactjs.org/link/warning-keys.

Thanks Dave! The only reason I didn't scrap the two components was for the animation; I know that was something we wanted for switching between them. I can delete them and look that up in the history if I need to (unless I forget it's there :).

I also remember seeing some unique key warnings as well. After a quick check it wasn't clear where exactly they were coming from, but I'll look at it more closely.

2021-03-30 14:14 UTC, dmfalke commented on src/EntityDiagram/Types.ts
>  export interface ShadingData {
Yeah, that animation doesn't seem to be complete, so it might be better to just start new when we know we want it.

2021-03-30 14:24 UTC, chowington commented
> 
> 
> Looks good Connor.
> 
> Just the duplicated type definition that needs attention, and I recommend merging #86 so the story can be adjusted on the fly by testers.
> 
> Could you also add a bit of padding/margin around the diagram (as per Steve's suggestion) and maybe also drop-shadow?

Thanks Bob!

Yeah, the duplicated type definition was so `EntityDiagram` wouldn't be dependent on `Types`, as the `Types` definitions would disappear along with the two separate ED components that needed them. I'll just finish the job and get rid of all of that according to Dave's request 👍 

I'll talk about the padding on Slack. Drop shadow exists on my branch along with controls 👍

2021-03-31 03:01 UTC, dmfalke approved these changes
These look good to me. I'll let @bobular make the final approval and merge.

2021-03-31 20:06 UTC, bobular commented
OK, I'll merge now.  Thanks!
Will you do another PR for the controls, drop-shadow etc?

2021-03-31 20:06 UTC, merged