[issues-69] add y-axis controls
VEuPathDB/web-components pull request #87
Opened 2021-03-30 17:59 UTC by moontrip

2021-03-31 14:26 UTC, dmfalke commented
This is looking good. I think the layout could use some work. I don't have any particular suggestions at the moment. A quick thought is that we should have a section for **X-AXIS CONTROLS**, in addition to **Y-AXIS CONTROLS**.

2021-03-31 14:58 UTC, bobular reviewed
Thanks for the PR!

I think more general discussion about plotControls is needed before going much further (but you could start the renaming and minor mods already).

2021-03-31 14:58 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +        {valueType === 'number' && toggleYLogScale && yLogScale !== undefined && (
log scale on the dependent axis should be OK for any valueType (number or date).  valueType is only describing the independentVariable.  Maybe it should be renamed to reflect that?

The conditional display of control widgets should only depend on
a) the true-ish state of the callback (here toggleYLogScale)
b) presence of other props required to draw the widget

See how Mike/Dave did it for the other widgets above: orientation, barLayout, selectedUnit

2021-03-31 14:58 UTC, bobular commented on src/hooks/usePlotControls.tsx
> +  const toggleYLogScale = () => dispatch({ type: 'histogram/toggleYLogScale' });
Because usePlotControls always returns a `toggleYLogScale` callback, the LogScale widget is shown in all the stories, not just the 'y-axis controls' story.

We'll discuss removing plotControls from the story altogether at this week's meeting.

2021-04-05 17:45 UTC, moontrip commented on src/components/plotControls/HistogramControls.tsx
> +  toggleYLogScale?: (yLogScale: boolean) => void;
@bobular I have complied with your suggestions. Also, reset button (UI only) ([issues #68](https://github.com/VEuPathDB/web-components/issues/68)) was added as well.

2021-04-05 17:46 UTC, moontrip commented on src/components/plotControls/HistogramControls.tsx
> +        {valueType === 'number' && toggleYLogScale && yLogScale !== undefined && (
@bobular following your suggestions, the conditions are simplified without checking valueType

2021-04-06 12:58 UTC, bobular reviewed
Looking good DK - I think maybe we should decide on the future of usePlotControls before merging (or working more) on this branch.  There's a topic on the agenda for tomorrow's meeting (which I can't attend, unfortunately).

2021-04-06 16:26 UTC, dmfalke commented
My main issue is still with the layout. I think it's difficult to parse. I think we should organize the individual controls into three main sections: **Y-Axis**, **X-Axis**, **General** (in that order). I also suggest we standardize on having labels above controls at all times. We can probably also get rid of the ****MIN**/MAX** labels for range selectors. They add an additional line and cause controls to be misaligned. Perhaps we need an option to hide the labels in the range widget.

Just for reference, this is an example of what we currently have on clinepidb.org:
![image](https://user-images.githubusercontent.com/365139/113744455-bb9f2600-96d2-11eb-8ef1-09febddbe483.png). I'm not suggesting we copy this, but it shows how we are clearly segregating x- and y-axis controls.

2021-04-07 17:44 UTC, moontrip commented
@dmfalke I have made a mockup like attached. Two questions arise: a) should "Log scale" be radio button style with texts like your screenshot?; b) should "Range" be aligned with input fields? It is doable but such a change will affect all range input forms like "Selected Range" etc.

![y-axis1](https://user-images.githubusercontent.com/12802305/113910950-654fe700-97a7-11eb-8940-748fca71fda2.png)

2021-04-07 20:53 UTC, dmfalke commented
This looks really good. I think the switch widget is fine for log scale. And I think putting range on the same line as the inputs is a good idea, if easy. Nice work!

2021-04-07 21:32 UTC, moontrip commented
@dmfalke Thank you for your review. I tried to make the range in-line but before committing my changes, I want to listen to your opinion: please see the below screenshot and see "SELECTED RANGE" at the top also is changed. Just let me know if you prefer this than two lines Range input fields :)

![y-axis4](https://user-images.githubusercontent.com/12802305/113937491-3ba6b800-97c7-11eb-970b-1ab4c588d4e9.png)

2021-04-07 21:43 UTC, dmfalke commented
Thanks @moontrip. I think two lines is better. Let's go with that. Thanks!

2021-04-07 21:57 UTC, moontrip commented
@dmfalke Thank you for your reviews and suggestions 👍 Corresponding commit is made with the new layout. Here is a screenshot for this commit which is very similar to earlier one (added some margin/padding)

![y-axis6](https://user-images.githubusercontent.com/12802305/113939913-9b529280-97ca-11eb-9230-ae64a9cdc918.png)

2021-04-08 02:55 UTC, moontrip commented
@dmfalke I realized that I did wrongfully use the reset all button to y-axis reset button. Will add like dependentAxisRangeReset button and use it for y-axis button.

2021-04-08 03:25 UTC, dmfalke commented
This is looking great! Do you plan to add the x-axis controls in this PR as well?

2021-04-08 03:32 UTC, moontrip commented
@dmfalke Thank you for your suggestion! Probably it is alright to use this ticket to add x-axis (independent axis) one at least. Will do that tomorrow morning :)

2021-04-08 14:36 UTC, dmfalke commented
> @bobular and @dmfalke, Following Dave's suggestion to add x-axis control group like I did for y-axis one above, I want to make sure of what kinds of controls should be in there. I think that Data Units (button group) , Bin Width (slider), and Selected Range (range) belong to x-axis control group, right? Initially I planned to use the term, independentAxis... for x-axis ones, but it may cause lots of additional changes to pre-existing ones (e.g., EDA Viz one, etc.), thus for now it is better to keep the current names (e.g., selectedRange, etc.) but group them under the umbrella of x-axis control box. What do you think?

I think those controls mostly sound right. I think selected range should remain outside of axis-specific controls. But the visible range should be added. And we should stick with the **x-axis** label for now.
 
> Also I was thinking of additional props to show/not to show the control group (x- or y-axis) (e.g., showDependentAxisControls), but it appears to me that each plot will probably have its own control component like HistogramControls component for histogram. Thus, such props seem not to be needed unless we will have a GeneralControls component.

Yeah, we can see how things look with other plot types.

2021-04-08 15:38 UTC, moontrip commented
@dmfalke Thank you for your information. I have update the overall layout and added a new x-axis range (named as independentAxisRange...). Here are two screenshots for number and date (with Data Units), respectively.

![axis-number1](https://user-images.githubusercontent.com/12802305/114055543-de5e4580-985e-11eb-9da1-72b0b2b2ebec.png)

![axis-date1](https://user-images.githubusercontent.com/12802305/114055569-e1f1cc80-985e-11eb-8144-16ef4dc1c711.png)

2021-04-09 10:42 UTC, bobular requested changes
I was wondering if we can merge this without a functional story to show all the controls working, but I think we can, after addressing the small issues above.

I noticed that there's some unfinished business with https://github.com/VEuPathDB/web-components/issues/61 which I'm going to reopen.  Basically, at some point, the HistogramControls and Histogram need to share the same independentAxisRange prop, but in Histogram.tsx it is still called yAxisRange (and, more importantly, is not yet a NumberOrDateRange).

2021-04-09 10:42 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +                // rangeBounds={selectedRangeBounds as DateRange}
on the dependent (y) axis, it's not appropriate to use `selectedRangeBounds` as bounds for the range controls - because `selectedRangeBounds` is in independent (x) space.

I know it's commented out, but this suggests it could be uncommented later, which would be misleading.

So I think we should remove all these commented-out  `rangeBounds={...}` props

2021-04-09 10:42 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +            y-Axis
(the same applies to the x-Axis box)

I think an empty x-Axis box will be displayed if none of the contained widgets are active.  Unfortunately, I think a large conditional (toggleDependentAxisLogScale || onDependentAxisRangeChange || onDependentAxisModeChange ...) is needed around the whole div.  This won't be great for maintenance (adding a new widget requires an edit in two places) so alternative suggestions gratefully received.

2021-04-09 10:42 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +        {/* commend this out as it moves to x-axis control group */}
Please remove the commented code that is already added back in another place.

2021-04-09 10:42 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +        {/* commend this out as it moves to x-axis control group */}
Please remove the commented code that is already added back in another place.

2021-04-09 12:37 UTC, moontrip commented on src/components/plotControls/HistogramControls.tsx
> +                // rangeBounds={selectedRangeBounds as DateRange}
@bobular thank you for your review and comments 👍 
I will remove them

2021-04-09 12:38 UTC, moontrip commented on src/components/plotControls/HistogramControls.tsx
> +            y-Axis
Yes I know the potential issue as I have made a comment earlier at https://github.com/VEuPathDB/web-components/pull/87#issuecomment-815767559, but citing in the following:

"Also I was thinking of additional props to show/not to show the control group (x- or y-axis) (e.g., showDependentAxisControls), but it appears to me that each plot will probably have its own control component like HistogramControls component for histogram. Thus, such props seem not to be needed unless we will have a GeneralControls component."

I thought that we would always show x- and y-axis controls for histogram? If there is a use case to hide those controls for histogram, then I think it is better to introduce a prop like my earlier comment above

2021-04-09 12:39 UTC, moontrip commented on src/components/plotControls/HistogramControls.tsx
> +        {/* commend this out as it moves to x-axis control group */}
yep and same to the below comment :)

2021-04-09 12:48 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +            y-Axis
I had an idea about the empty subsections.

The subsection containers can be handled by a component that renders nothing when `children.length === 0` (or similar).

But you may be correct about always showing x- and y-axis controls for a histogram!

2021-04-09 15:01 UTC, dmfalke commented on src/components/plotControls/HistogramControls.tsx
> +            y-Axis
Don't quote me on this, but it might be possible to use a css rule like this:
```css
.AxisControlContainer:empty {
  display: none;
}
```
See https://developer.mozilla.org/en-US/docs/Web/CSS/:empty

2021-04-12 15:47 UTC, bobular commented on src/components/plotControls/HistogramControls.tsx
> +            y-Axis
Hi DK - did you decide on a solution for the "empty subsection" issue or are we going to skip this for now?

2021-04-12 16:30 UTC, moontrip commented on src/components/plotControls/HistogramControls.tsx
> +            y-Axis
Hi @bobular I have tested the CSS but it does not work properly, perhaps because the condition of "empty" is quite strict? (even no single space allowed). I think it is better to be handled at another ticket. 

Currently working on #61 within this PR

2021-04-12 17:44 UTC, moontrip commented
- merged master
- #61 concerning yAxisRange props: relevant component props are changed from yAxisRange to dependentAxisRange, including Histogram component. Some local variables using the word, yAxisRange..., are not changed

2021-04-13 16:17 UTC, dmfalke reviewed
Looking at this picture, there are some things that can be improved:
![image](https://user-images.githubusercontent.com/365139/114585416-9b7ee200-9c51-11eb-9a39-0ad05719c86f.png)

1. x- and y-axis controls should be side-by-side. Maybe put them in a flex container?
2. The reset button text should not wrap
3. Generally, prefer to use `em` rather than `px` lengths.

Also, I'm not crazy about inline styles, but they are okay for now. We can address as a follow-up. I started playing with `useStyles` from the material-ui package, which adds theme-based support, which might be really useful in the future. Until we assess exactly what direction we want to go (traditional css/scss vs css-in-js), we can leave the inline styles as-is.

2021-04-13 16:49 UTC, moontrip commented
@dmfalke actually they are side by side via inline-flex: I can see both correctly at (Plot Controls) Histogram->Y-Axis controls under both Chrome and Firefox as I showed in my previous screenshots. Please note that I didn't put widths for each group (y- or x-axis box) and it depends on the width of the outer box. But the default value (or min width) of the range input field by the Material UI may be a bit larger though. So, if the outer box has smaller width, then the y- and x-axis boxes will be located at upper and lower sides, instead of side-by-side: this is the case for (Plots) Histogram->Range Selection. 

As for the reset button, I found strange that it shows correctly at Chrome but not at Firefox. Perhaps the width of the button may be a bit smaller: will check it out

2021-04-13 17:01 UTC, dmfalke commented
I see. I was looking at a histogram story. I think it was the first one.

2021-04-13 17:49 UTC, moontrip commented
@dmfalke I found a reason that the range input fields (with the text "TO") is comprised of dispay:flex thus they occupies all width depending on the control box size. A quick solution is to set width for the box, like width: 480 (30em) for both control boxes and revisit more detailed layout in the near future. Also fixed the reset button one.

For the "em", yeah actually I used px and em together for the control boxes. Since there are lots of usage for px at other places beyond x- and y-axis control boxes at <HistogramControls> component, I tried to change them to em as many as possible. 

I have pushed those changes so can you please check them out?

2021-04-13 18:13 UTC, dmfalke approved these changes
Thanks @moontrip, the reset buttons look better. The axis controls are still appearing on separate lines for me, but maybe it will be okay on the eda website and we can address this some other time.

Are there any other remaining TODOs for this PR?

2021-04-13 18:17 UTC, moontrip commented
@dmfalke Thank you for your quick review. It is quite strange that I can see them correctly at both Chrome and Firefox. We will see :)

I think no TODOs are left in this issue as I also addressed Bob's request in this PR too (https://github.com/VEuPathDB/web-components/pull/87#pullrequestreview-632255527)

2021-04-13 20:01 UTC, dmfalke commented
@moontrip are these issues related?
* https://github.com/VEuPathDB/web-components/issues/70
* https://github.com/VEuPathDB/web-components/issues/66

2021-04-13 20:08 UTC, moontrip commented
@dmfalke #70 involves mouse-based control for zooming the selected range in the plot, while #66 is text-based control of selected range only (no zooming involved). Thus, those two are technically different.

2021-04-13 20:16 UTC, dmfalke commented
Ah, ok. We can keep #70 open. #66 was reinterpreted as fixing a bug where the text box was not editable. Are you saying that wasn't addressed in this branch? I thought you mentioned you were working on it, and I assumed it was in this branch.

2021-04-13 20:22 UTC, dmfalke commented
I'm going to merge this. If #66 is still an issue, I think it will be addressed by PR #99.

2021-04-13 20:23 UTC, dmfalke approved these changes

2021-04-13 20:24 UTC, merged

2021-04-13 20:24 UTC, moontrip commented
@dmfalke Ah... there are so many similar numbers for issues so you might have been confused :) The one Bob raised before was #61, which I have added fixes in this PR, not #66. The latter is more related to the slider one you worked #99, which I have independently been working with my approach. Honestly, I am not quite sure if mine would be better than the solution addressed at #99 but I will make a PR today anyway - will make you as a reviewer :)

2021-04-13 20:27 UTC, dmfalke commented
Okay. I just misunderstood. When you said you were working on it, I thought you meant as a part of this PR. No worries!