Slider with auxiliary text input
VEuPathDB/web-components pull request #99
Opened 2021-04-09 23:04 UTC by bobular

Just realised I spelled auxiliary wrong in the story file...

I made the draft PR to make it easier to discuss a change that @dmfalke made that seemed to have broken all number/date text input fields.  I'll make a specific comment below.

2021-04-09 23:08 UTC, bobular commented on src/components/widgets/NumberAndDateInputs.tsx
> +    return newValue;
Dave did this while making all input widgets 'controlled' - but I don't see why, so I reverted it here.  Still need to do lots of testing.

It may be the explanation for #66 - @moontrip

2021-04-09 23:22 UTC, dmfalke commented on src/components/widgets/NumberAndDateInputs.tsx
> +    return newValue;
I did that to prevent calling `onChange` on the initial render. Perhaps instead we should update the `useEffect` hook just below and only call `onChange` if `newValue != null && newValue !== value`?

2021-04-10 18:06 UTC, bobular commented on src/components/widgets/NumberAndDateInputs.tsx
> +    return newValue;
Sounds good - I'll have a play with that.

2021-04-12 13:33 UTC, bobular commented
New slider with auxiliary text-input box is working - it just needs the `showTextInput={true}` prop.

Lots of tidy-up was done in number and date inputs, and their stories - removing uncontrolled stories, making the controlled value prop mandatory and much more.

No known issues - other than perhaps the logic that automatically sets the width of the text box of the enhanced slider could be moved inside the NumerAndDateInputs.tsx code.  I'll add a comment to locate that code.

2021-04-12 13:34 UTC, bobular commented on src/components/widgets/Slider.tsx
> +            width:
Here's the automatic width code.

Could possibly go into NumberInput and DateInput ?

2021-04-12 18:58 UTC, dmfalke requested changes
I've left some inline comments.

2021-04-12 18:58 UTC, dmfalke commented on src/components/widgets/NumberAndDateInputs.tsx
> +  value: M;
Shouldn't we allow an empty value?

2021-04-12 18:58 UTC, dmfalke commented on src/components/widgets/NumberAndDateInputs.tsx
> +  onValueChange: (newValue: NumberOrDate) => void;
This could be useful if we wanted to include a "clear value" button, or something similar.

2021-04-12 18:58 UTC, dmfalke commented on src/components/widgets/NumberAndDateInputs.tsx
> +    (event: any) => {
```suggestion
    (event: React.ChangeEvent<HTMLInputElement>) => {
```

2021-04-12 21:49 UTC, bobular commented on src/components/widgets/NumberAndDateInputs.tsx
> +  value: M;
See next comment

2021-04-12 22:04 UTC, bobular commented on src/components/widgets/NumberAndDateInputs.tsx
> +  onValueChange: (newValue: NumberOrDate) => void;
I originally wanted to keep the ability to clear the inputs.  For one thing, it makes it easier to edit the contents if you can clear it before typing in the number you want.

However, there were problems...

React complained (in the console.log) about switching between controlled and uncontrolled components when the box is cleared. I think the problem is when the prop's value switches between defined and undefined.  I tried to use `null` instead but that didn't seem to help. The React warning suggested using empty string as a value, which I tried, e.g.

props
```
value: M | '';
onValueChange: (newValue: NumberOrDate | '') => void;
```

But on clearing the box it still went to zero, not empty.  (I'm pretty sure there was appropriate code in `boundsCheckedValue` to handle the empty string.)

I'll have another go though. Now the code is cleaned up a bit, I might be able to get it working more easily.

2021-04-12 22:13 UTC, bobular commented on src/components/widgets/NumberAndDateInputs.tsx
> +  onValueChange: (newValue: NumberOrDate) => void;
Oh...

`Number('') === 0`

2021-04-12 23:46 UTC, bobular commented
The text field inputs can now be cleared by the user, but...  there is still one issue

In this story `/story/widgets-number-input--silent-bounds-check` for example, you can't easily clear the input because a single backspace will create the value '1' which is outside the range, so is 'fixed' to 10.  The only way to clear it is to select everything in the box, and then press backspace.

I tried adding debounce logic similar to Slider.tsx but that doesn't work.  What's needed is debouncing *only* for the typing input, not the up/down arrow (or keyboard arrows).  

A non-debouncing solution would be to automatically select-all inside the input field when the user clicks in it.

2021-04-13 01:20 UTC, moontrip commented
@bobular 

> A non-debouncing solution would be to automatically select-all inside the input field when the user clicks in it.

I am not quite sure whether you already knew, but just in case, it can be achieved as follows:

`const handleFocus = (event: React.FocusEvent<HTMLInputElement>) => event.target.select();`

then add onFocus prop at the child component:

`onFocus={handleFocus}`

Actually I am adding it as a part of my current work, #66 adjusting selected range at NumberAndDateInputs.tsx component, so you may not need to make it if you plan to use it at the same file/component: I am using onFocus prop at TextField component in this case.

2021-04-13 02:16 UTC, dmfalke commented
Another thing to try in `NumberAndDateInputs`:
- Use component state for values, similar to `Slider`
- Allow invalid values
- Display an error message for invalid values
- Only call `props.onChange` for valid values
- Debounce the call to `props.onChange` to allow valid intermediate values without triggering a change

This should allow users to clear the input field before typing a new value. The range component wouldn't need to do this trick, since it would only call its `props.onChange` if the input calls its `props.onChange`.

If I have time tomorrow morning, I will try this out and report back.

2021-04-13 10:57 UTC, bobular commented
Thanks @moontrip - I didn't know that!

@dmfalke - that sounds worth a try - is `''` still a valid value for the externally controlled prop?

I'll have a go tonight if you don't find time today.

2021-04-13 11:11 UTC, bobular commented
Because I'm not working until around 2pm EST, it would be a good time to coordinate between this PR and DK's work for #66 - because it sounds like there is overlap.  So please feel free to do anything with this branch until that time.

2021-04-13 16:01 UTC, dmfalke commented
@bobular @moontrip I pushed a commit that implements my suggestion. I've tested it and it seems to work pretty well. Please take a look at your convenience.

2021-04-13 21:51 UTC, bobular commented
That looks great Dave - I have given it a thorough test and made one change so that the 
`/story/widgets-number-input--controlled-bounds` story works (changing the bounds causes the bounds checking to be done again)

I've noticed one remaining thing (sorry!)
I don't fully understand the logic behind the debounce cancel at L143 so would appreciate having that explained...

But I played around with and without that line canceled out.

As is: If you hold down on the up-arrow and let it repeat to an out-of-range value (e.g. 15 in `/story/widgets-number-input--controlled-bounded`) I notice that the debouncedOnChange never gets called and the externally controlled value is unchanged.

L143 (cancel) commented out: If you hold down up-arrow as described above, the external value gets set to 5 (which might be desired?)  But at some point that 5 gets transfered to localValue and so the displayed value goes down to 5 temporarily and then keeps incrementing upward (if the user is still holding down the up arrow).  So the behaviour with the controlled value is better (arguably) but the on-screen behaviour is a bit unnerving.

I'll see if I can figure out a simple solution, but we could discuss tomorrow.

2021-04-13 22:59 UTC, bobular commented
I've pushed a commit that (in my opinion) solves the problem of going out of range but not setting the controlled value to the limit of the range (as described above).

If you up-arrow out of range, when you release the key or mouse button, the controlled value will be set to 5, and after a 500ms warning, the displayed value will also be set to 5.  If you increase the displayed value again, it will not be "auto-corrected" back to 5 (because the controlled value of 5 has never changed).

I added a new story to show the behaviour when an externally provided value is out of range (nothing crazy happens - the out-of-range value is displayed with a warning).

I think this is a pretty OK solution all round.  It works nicely for the number-slider `/story/widgets-slider--auxiliary-text-input` - if you really want go out of range, you can, but your first attempt will be "corrected" and the controlled value will of course stay within the bounds.

2021-04-14 13:26 UTC, dmfalke commented
> I don't fully understand the logic behind the debounce cancel at L143 so would appreciate having that explained...

The idea here is that we don't want to notify the consumer of a stale value. Without this line, if `localValue` goes out-of-bounds or empty, a pending call to `onValueChange` will trigger the consumer (e.g., parent) of this component to update with an out-of-date value, which will cause the input's value to change "under the user's mouse". Thus, we have to cancel the pending call. Another option would be to call the `flush` method, which give you your desired behavior: the consumer will be notified of the last in-bounds value.

I haven't looked at your latest, but based on your description, I am concerned about changing the value like that. I will try to take a look... or maybe you can try my suggestion and compare the UX?

2021-04-14 19:13 UTC, bobular commented
Thanks for the explanation.

> Another option would be to call the `flush` method, which give you your desired behavior: the consumer will be notified of the last in-bounds value.
> 
> I haven't looked at your latest, but based on your description, I am concerned about changing the value like that. I will try to take a look... or maybe you can try my suggestion and compare the UX?

It does work, perfectly! Thanks again!

2021-04-14 19:18 UTC, bobular reviewed
I can't approve the requested changes.  @dmfalke please could you?

2021-04-14 19:36 UTC, dmfalke approved these changes

2021-04-14 19:42 UTC, merged